[package]
name = "spacestate"
version = "0.1.0"
authors = ["cfstras <cfstras@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
prost = "0.6"
rustls = "0.17.0"
webpki = "0.21.2"
webpki-roots = "0.19.0"
fake_clock = "0.3.0"

[build-dependencies]
prost-build = "0.6"

[profile.release]
lto = true
