name: Rust

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: Swatinem/rust-cache@v2
    - name: Preconditions
      run: apt-get update && apt-get install --no-install-recommends -y protobuf-compiler

    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: jdsl
        path: target/release/spacestate
